
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'
      
    - name: Set credentials value
      run: echo ${{ secrets.Test_Secrets }} >> internal/sharefile/credentials.yaml 
    
    - name: Check credentials value
      id: cred_values
      run: echo ::set-output name=credentials_value::$(cat internal/sharefile/credentials.yaml)
    
    - name: Test output
      run: echo ${{ steps.cred_values.outputs.credentials_value }}

